
echo
echo
echo "                                     _.._      _"
echo "                                    (\\   \`-../' \`\\"
echo "                           _..--..__|_)      )   )\`-."
echo "                          (_       |  |     /   |    \`-..,,"
echo "                          | )      |  |    (   ,'         )"
echo "                          |,'\\     (  (    '  (          ,'"
echo "                     __..-'   \\     )  )      |         ,\\.__"
echo "                    \`\\         \\    \`. \`.     )        ,'    \`\`--,"
echo "                      \`\\        \\    )  )    (        ,'        /"
echo "                        \`\\_      |   (  (    |       (        ,'\"Y8a,_"
echo "                    __,,ad8b,    (   \`. \`.   |      ,'     _,'     \`\"\"Y8a,_"
echo "            __,,aad8P\"\"'' _,8b    )   )  )   |     ,'   _,d88b          \`\"\"Y8a"
echo "      _,aad8P\"\"''       ,d8888b   )   (  (   (    (  ,d8888P\"'    __,,aadd8PP8"
echo "      8\"Y8b,_           \`Y888888a,(,,,,),,),aabaaadgd8PP\"'__,,aadd8PP\"\"''    8"
echo "      8   \"\"Y8a,_          \`\`\"\"YYYYY88888PPPP\"\"\"''__,,aadd8PP\"\"''            8"
echo "      8       \"\"Y8a,_                     __,,aadd8PP\"\"''                    8"
echo "      8           \"\"Y8a,_         __,,aadd8PP\"\"''                            8"
echo "      8               \"\"Y8a,,,aadd8PP\"\"''                                    8"
echo "      8                   \"8P\"\"''                                           _8"
echo "      8                    8                                         _,,aadd88"
echo "      8b,_                 8                                  _,,aadd88888888P"
echo "      8888ba,              8                           _,,aadd88888888PP\"\"''"
echo "       \`\"Y8888b,_          8                    _,,aadd88888888PP\"\"''"
echo "          \`\"Y8888ba,       8             _,,aadd88888888PP\"\"''"
echo "             \`\"Y88888b,_   8      _,,aadd88888888PP\"\"''"
echo "                 \"\"88888ba,8,,aadd88888888PP\"\"''"
echo "                    \`\"Y888888888888PP\"\"''"
echo "                       \`\"Y88PP\"\"''"
echo "                           \""
echo
